### ISSUE TITLE
Cydia Substrate not coming up in Cydia search or installing in first-time jailbreak

### ISSUE THREAD

**Issue by marleyqp** [checkra1n/BugTracker#1002]
iPhone 7 Plus, i'm using 0.9.8.1on Ubuntu 20.04 Linux.
When I first jailbroke with checkra1n, I installed Cydia and attempted to install tweaks, but instead of installing Substrate, it installs Substitute. And I have to downgrade Substrate Compatibility layer to get my tweaks to work.

**Comment by eglacias** [comment]
Instead, I manually install from filza latest checkra1n copy of mobilesubstrate in order to get out of basically a safe mode like state every single time I jailbreak. Before that, applications will work, but not system tweaks.  Try finding the latest copy of the above file, it should solve your problem.  I believe I got it from the uncover jailbreak and copied it over, but then again I remember it is from checkra1n, at some point I must’ve gotten it working with tweaks, at which point that file was existent. Anyway I have a copy of it if needed!

**Comment by marleyqp** [comment]
Solved. I removed Electra's iOS Utilities repo and now it comes up.
Closing.
