### ISSUE TITLE
Cant hook viewcontroller ios app

### ISSUE THREAD

**Issue by illidandh** [checkra1n/BugTracker#1061]
**Tell us about your setup:**
1. iPhone 6
2. iOS 12.4.4
3. version of checkra1n  CLI?
4. System MACOS

I try develop some tweak , its work perfectly with springboard but its doesn't work with app like facebook, youtube. Also tweaks like youtube tools, certube, spotify lyric don't work. Anyone know what is wrong, sorry for my bad english . Thank you.

**Comment by Siguza** [comment]
Given the fact that it seems to work for virtually everyone else, I can only guess that it's either a set of incompatible tweaks, or something like NoSub that prevents injection into certain processes.

Either way, this issue seems to be unrelated to both checkra1n and Substrate itself, so I will close this ticket. I can loosely suggest you hit up the Jailbreak Discord, they should have the capacity to help you debug this.
