### ISSUE TITLE
DFU guide doesn't work for iPhone8/X

### ISSUE THREAD

**Issue by CircuitSavage** [checkra1n/BugTracker#12]
**What device + iOS version are you on?**
Iphone X, 13.1.3

**What are the steps to reproduce the issue?**
1.Just follow the DFU Guide
2.
3.
...

**What do you expect, and what is happening instead?**
I expected it to go into DFU mode, but it keeps booting to springboard.

**Any other info, error logs, screenshots, ...?**
No, sorry.

**Comment by steven30303** [comment]
Not a Chechra1n issue. But try to follow this guide https://youtu.be/a70jiFqMGX0?t=138

**Comment by CircuitSavage** [comment]
I've followed the steps exactly around 10 times now.

**Comment by cat24max** [comment]
Yea, going into DFU on iPhone X seems to be impossible.

**Comment by CircuitSavage** [comment]
Exactly.

**Comment by Brandon-T** [comment]
It does work perfectly fine..

1. Leave the device on..
2. Press Volume Up, then Volume Down, then power and hold it until the screen goes black (hard reset).
3. When the screen goes black, release the power and HOLD BOTH power and volume down (quickly) at the same time for 7 seconds (count to 7).
4. Release power but keep holding volume down for 10 seconds.
5. Run checkra1n.

**Comment by cjf99** [comment]
For me it's not working either. My phone always just boots into normal mode on both methods.

**Comment by cat24max** [comment]
@Brandon-T These instructions do NOT work.

These do: https://www.hardreset.info/devices/apple/apple-iphone-x/dfu-mode/

Checkra1ns instructions for the iP X are wrong. Especially releasing the power button and then pressing both again is wrong. Just never release the power button and it works.

**Comment by Brandon-T** [comment]
Lol I have an iPhone-X it does work. You're just doing it too slow. Timing is everything. But as long as you found something that works for you it's all well and good.

**Comment by cat24max** [comment]
@Brandon-T No, they don't. And apparently I am not the only one. The timings in checkra1in are definitely wrong.

Though DFU doesn't help me because #33

**Comment by Brandon-T** [comment]
@cat24max https://i.imgur.com/d7xl3Uz.mp4 (notice at ~0:27 [between 0:25 and 0:28] how fast I released and pressed power again.. this is the HARDEST part when doing it from recovery mode which is why the steps I had listed did it from a hard reset instead which is MUCH EASIER and doesn't require releasing the power button on the second phase [It's optional. You can if you want]).

It does work!.. Like I said before. It's 1000% about EXACT timing which is why people have trouble with it.

Here's another.. You can see I have Checkra1n running and following the countdown steps (look at the reflection of the iPhone's screen): https://i.imgur.com/AqLuo46.mp4

So it does work.. but it's 100% about timing. If you even miss it for 1 second, it will NOT work. It's way easier to do it when the device is ON and you do a hard-reset then hold volume down right after it resets.

While I agree it's hard, I cannot say the instructions are wrong because I can actually do them and I followed them exact and they work and I've video taped it 3 times.. they're just not the most ideal or easiest timings to follow.

P.S.: I also get stuck: https://github.com/checkra1n/BugTracker/issues/14

**Comment by cat24max** [comment]
@Brandon-T Yea, doesn't work on my X. Going into DFU from Recovery is impossible.

**Comment by Shadowedstalker** [comment]
DFU mode is not 'impossible' on devices, One thing that has been an issue is the timing is off in Checkra1n. watch the device. Hold power until it goes black, release and hold power and volume down for 5 second (count) release the power buttton and hold the volume down. watch Checkra1n it will tell you it has successfully entered DFU mode.

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.

**Comment by iMonZ** [comment]
> 0.9.5 fixes these issues, with the new DFU sequence.

same issue with iphone 7
