### ISSUE TITLE
Mounting Samba drives in Files.app fails due to Cydia Substrate injecting into GSSCred

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1467]
**Tell us about your setup:**
1. What iDevice are you using? iPhone10,3
2. On what version of iOS is it? iOS 13.5
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Hackintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
1. Jailbreak with the latest checkra1n
2. Open Files.app and try to connect to a properly set up samba server
3. Connection hangs and GSSCred crashes in the background whereas the same doesn’t happen when device isn’t jailbroken

**What do you expect, and what is happening instead?**
See above.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No, since Cydia Substrate is probably the problem here and it’s disabled in that state.

**Any other info, error logs, screenshots, ...?**
Unc0ver seems to have partially fixed the issue as it’s using Substitute which automatically filters GSSCred out. Currently it seems to be working as long as Substrate isn’t used.

**Comment by Siguza** [comment]
Issue reproduced. Thanks for the amount of detail.

**Comment by RonaldRegister** [comment]
Great to see activity, thank you guys for your work. If you need help testing, let me know. 13.5 Checkra1n.

**Comment by newhacker1746** [comment]
Managed to fish a crashlog from syslog:
```
Jun 14 15:47:35 Daniel-Rodriguezs-iPhone ReportCrash[22183] <Notice>: Notice: This report is abbreviated for syslog inclusion because it could not be saved to disk.
Symbolication may be possible by manually cleaning up and including the Binary Image section of a full report from this same device -- good luck!
Jun 14 15:47:35 Daniel-Rodriguezs-iPhone ReportCrash[22183] <Notice>: Process:             GSSCred [22182]
Path:                /System/Library/Frameworks/GSS.framework/Helpers/GSSCred
OS Version:          iPhone OS 13.4.1 (17E262)
Jun 14 15:47:35 Daniel-Rodriguezs-iPhone ReportCrash[22183] <Notice>: Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001a602697c
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [22182]
Triggered by Thread:  0
Jun 14 15:47:35 Daniel-Rodriguezs-iPhone ReportCrash[22183] <Notice>: Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_trace.dylib         	0x00000001a602697c 0x1a601a000 + 51580
1   libsystem_trace.dylib         	0x00000001a602697c 0x1a601a000 + 51580
2   GSSCred                       	0x0000000102a7a510 0x102a74000 + 25872
3   libdyld.dylib                 	0x00000001a6275800 0x1a6274000 + 6144
Jun 14 15:47:35 Daniel-Rodriguezs-iPhone ReportCrash[22183] <Notice>: Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x00000001f30a7688  x10: 0x00000001f30a7680  x11: 0x0000000000000002
   x12: 0x00000000fffffffd  x13: 0x0000010000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000001  x18: 0x0000000000000000  x19: 0x0000000000000001
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x000000016d38bd50   fp: 0x000000016d38bce0   lr: 0x00000001a602697c
    sp: 0x000000016d38bcd0   pc: 0x00000001a602697c cpsr: 0x60000000
   esr: 0xf2000001  Address size fault
```

**Comment by Siguza** [comment]
Thanks, but no need.  
@sbingner already figured out the underlying issue, we just... actually depend on saurik to fix it. :/

**Comment by shadowscott** [comment]
@Siguza I believe this was fixed in Substitute right? Is it the same kind of fix just in Substrate but requires assistance from saurik?

**Comment by gueswho1992** [comment]
Open

**Comment by saurik** [comment]
So some seriously angry user on reddit linked to this issue a bit ago in what felt like an almost tangential nastygram about how much I suck (seemingly because I haven't magically found all of the one-in-a-thousand threads that are relevant) :/.

FWIW, my (mis)understanding of this issue from @sbingner (which is _not_ to say this misunderstanding was his fault, but to acknowledge I talked to him about this and this is what happened) was: 1) that it was caused by extensions using oslog before GSSCreds did some initialization that relied on nothing having previously already used oslog; 2) that it was explicitly not caused by Substrate alone (this detail is critical: it indicated that this was not, inherently, a bug with Substrate); and 3) that it could be fixed by an extension (which was a solution he explicitly suggested; I figured this would be the default fix).

Meanwhile, as background, I strongly believe: 1) that Substrate should _not_ be in the business of accumulating one-off patches to random processes (I would rather just ban Substrate from entering the process until I can figure out what's wrong to avoid "messing with" the process in a way that breaks another developer); 2) that oslog (though... I have an update on this in a later paragraph) should probably be avoided by extension developers during constructors (as it apparently has side effects, which should be avoided at all costs inside of a constructor); and 3) that if a third-party wants to release a "support ill-advised logging frameworks ;P extension" that other extensions could depend on in order to allow them to use oslog _despite_ it having weird side effects, that that would be a legitimate usage of community maintenance.

The proposed solution--to fix this using an extension: which, again, is what was mentioned by Sam, and which I figured is what would end up happening--sounded to fix the problem no matter what injection or hooking mechanism was being used by the user, as opposed to it merely being fixed for ones which went out of their way to add one-off workaround for this particular process. Notably, it also would better support the scenario of _multiple_ loaders all operating in the process _at the same time_, which is something that I'd prefer to attempt to continue to support even as it feels like an elusive dream these days due to how much mucking around I am doing inside of dyld (and, to that end, I occasionally actively verify that Substrate's loader doesn't conflict with some older loaders on iOS 3, even though I feel those projects were ill-conceived).

However, now that I see an actual _reproduction_ for this issue (which turns out to be equivalent to just running the code at the command line), and now that I actually have a device where I've used checkra1n myself (to work on filing a libobjc bug), I tried it myself, and in fact Substrate _does_ seem to _itself_ cause the crash of GSSCreds, as I can make it happen even with no extensions installed :(. For any avoidance of doubt: any bug that is caused by Substrate without any extensions installed and which isn't in some sense "part of the jailbreak"--and so maybe should be fixed by a Substrate "server plugin" as oppose to a Substrate behavior; though the boundary on this is up for debate as there's a place where the jailbreak's job can be considered "done" and it is up to Substrate to carry on the rest of the way--is something I'm more than happy to fix... you just need to tell me what's happening (as I _guarantee_ to everyone that I won't know if no one bothers to tell me).

I have thereby sent 0.9.7103 for release, which I will claim solves this problem. Note that, as it seems like I've accumulated a number of workarounds for my usage of even ASL in Substrate and I think half of my ban-list is due to random things doing logging, I'm going to do a tactical retreat from any usage of this logging mechanism at all from Substrate and come up with a better solution for my attempts at diagnostics (particularly since I'm getting the impression that no one even knows where ASL logs go anymore... I mean, _I don't_... and I'm the one logging everything there!! lol omg... when I want to actually see my own logs I seriously swap in a different logging backend, so why do I even log things at all, really?... _but I digress_). So: my personal strong recommendation now is "using any kind of logging framework should be considered a dangerous side effect during a Substrate extension initializer: do whatever you can to _only_ perform hooks and comparisons at that time".

**Comment by ghost** [comment]
Haha just finished reading the whole comment and can confirm this has been fixed after updating to the lastest Substrate (0.9.7103). Thanks so much @saurik for the detailed, clarified, and developer-friendly response. Btw definitely looking forward to the new debugging system that might end up replacing ASL; should make Substrate much more streamlined :)

Personally Substrate’s already been really stable for me aside from this minor issue. Again, thank you for this awesome piece of work :D

**Comment by Siguza** [comment]
@saurik Thanks a ton for fixing this, and for coming here in the first place.  
Apologies for not reaching out to you directly, I (and the rest of the team, I presume) had relied on Sam being the channel to you. And all my attempts to reach you over the years have failed, so I long assumed you weren't really reachable for the general public anymore / drowning in notifications and I just wasn't getting through the noise. But I'm more than happy to involve you on relevant issues - would tagging you here on GitHub suffice?

**Comment by saurik** [comment]
Yes: honestly I have found these various issue threads on GitHub to be the most productive ways of dealing with issues, so please @-mention me on anything that comes up that seems relevant.

**Comment by shadowscott** [comment]
Thank you all for resolving this. Not only was this affecting SMB shares but also logging into Office 365 on mobile.

**Comment by RonaldRegister** [comment]
Much appreciated. Can confirm it's working now. (although not very stable but thats the problem of the Files.app in general)
Thanks for everyone involved.
