### ISSUE TITLE
How to manually get apt/dpkg working without clicking "Install Cydia" button in loader.app?

### ISSUE THREAD

**Issue by mailinglists35** [checkra1n/BugTracker#1531]
I want to install stuff only via ssh. But unless I tap "Cydia" in the loader.app, I get no dpkg / apt packages installed. I have neither found these in the binpack or loader.app. 

I assume then that these are downloaded on the fly when user taps "Cydia".

If that is true, would you mind sharing the stuff I should manually download and decompress into the phone, without installing Cydia?

Thank you!

**Comment by Siguza** [comment]
The current loader config can be accessed [here](https://assets.checkra.in/loader/config.json), and contains download URLs for both the Cydia bundle and the core bootstrap.

Note though that checkra1n actually keeps the rootFS readonly until you choose to install Cydia from the loader.  
In order to manually make it writeable, run:

    mount -o rw,union,update /

Then, to have checkra1n remount it automatically on each boot, do:

    touch /.mount_rw

And finally you'll want to rename the APFS snapshot, because otherwise iOS will revert the rootFS on the next boot.  
Get the name of the snapshot with:

    snappy -f / -l

And then rename it with:

    snappy -f / -r [name] -t orig-fs

**Comment by mailinglists35** [comment]
absolutely wonderful explanation, many many thanks!

**Comment by mailinglists35** [comment]
"checkra1n ssh only" so I know I'll find this when searching next time for checkra1n ssh only
