### ISSUE TITLE
I am having issue with my jailbroken device

### ISSUE THREAD

**Issue by Mohitsharma1234** [checkra1n/BugTracker#1635]
Hi Team Checkrain ,
 
                   I was on iOS 13.5 jailbroken through checkrein and was running good, few week ago I updated to iOS 14 beta and forget to uninstall jailbreak & now I can't use any banking apps because its saying device jail broken but i don't have checkrein or cydia on my menu. 

please reply as soon as possible

you all are my last hope

**Comment by demhademha** [comment]
Since there is currently no way to restore rootfs on ios 14, you'll need to do a device restore via iTunes.

**Comment by Mohitsharma1234** [comment]
There is option to restore to 13.6

Is there jailbreak possible on it?

**Comment by demhademha** [comment]
That is correct, you can use checkra1n on iOS 13.6, just make sure to enable  "allow untested ios/tvOS versions" in options

**Comment by Mohitsharma1234** [comment]
Ok sir let me try

Thank uuu

**Comment by Siguza** [comment]
Yes, you will need to go back to 13.6.1 at the moment. Be advised though that the data partition format has changed, and downgrading from 14.x to 13.x will make you lose your data! So make sure to backup your data beforehand, and restore it after the downgrade.

Closing this though, since there's nothing we can do on our end (besides iOS 14 support, which is being worked on).
