### ISSUE TITLE
[Feature Request] Reinstall Cydia directly from loader

### ISSUE THREAD

**Issue by worf1337** [checkra1n/BugTracker#1706]
Most of the time I want to reinstall cydia because I corrupted it.

At the moment the loader opens Cydia to reinstall it (which obviously crashes)

It would be great if it directly reinstalled it, like the way it installs cydia when jailbreaking for the first time

**Comment by Siguza** [comment]
The problem is that this can't be properly done. The only way to properly reinstall Cydia is via apt/dpkg, or you will mess up the dpkg state. The loader's purpose is to install things _before_ apt/dpkg are available.

Essentially you have two alternatives:

- Connect via SSH and invoke `apt` from the command line to reinstall Cydia.
- Use the "Restore System" option in the loader, then install the bootstrap anew (this will also wipe all other packages).

**Comment by worf1337** [comment]
That's a shame :/ 
Oh well.

**Comment by worf1337** [comment]
Perhaps the loader could run `apt reinstall cydia`, maybe
