### ISSUE TITLE
0.11.0 broken pongoOS Modules

### ISSUE THREAD

**Issue by Naville** [checkra1n/BugTracker#1744]
**Tell us about your setup:**
1. iPhone 8 13.6.1 checkra1n0.11.0 macOS USB-Cable

**What are the steps to reproduce the issue?**
1.  Load [SVC Stalker](https://github.com/jsherman212/svc_stalker)
...

**What do you expect, and what is happening instead?**
The module works perfectly fine in previous checkra1n version but shows some error about missing patch on v0.11.0

**Comment by Naville** [comment]
Logs:
panic: missing patch

**Comment by Naville** [comment]
Reverting to 0.10.2 resolves the issue so that means there is definitely something broken here

**Comment by ShawnTimez** [comment]
I agree with Naville 100 percent.

I see a lot of folks inconclusive on what to point the fingers at. Its checkra1n. Checkra1n is the problem its not the generation of device unless your going past iPhone X the ipad 5th gen and below should be supported. This processors are exploitable.

A lot of folks seems to forget beta 0.11.0 checkra1n is needed to jailbreak ios 14. However ios 13.7 that is not the case.

If beta 0.11.0 supports  ios 12-13-14 as it claims
Why won't it successfully jailbreak any device ive tried only running ios 13 while checkra1n 10.2 does it everytime all day.

I've never gotten checkra1n 0.11.0 to work on any device running 13.7

I tried USB bootrain for windows. I tried Ubuntu Linux dual booting. I even tried on actual mac os I borrowed one and installed it and tried it. 0.11.0 never works. Always errors -77 or -79 sometimes you get a different error based on which software you used whether it be Linux or max or bootra1n for windows.

I've tried with different cables and name brand cables at that. First party usb A to lightening. Its not the cable. Its checkra1n version 0.11.0

I couldn't thank the checkra1n team more honestly. But this is a issue unaddressed. And folks seem to not know where the problem lays.

**Comment by Siguza** [comment]
Ok, thing is: we switched ABIs in 0.11.0.  
The only reason we've been on AAPCS is because that enabled us to use an off-the-shelf toolchain + embedded standard library offered by ARM. That presented some issues however, most notably clang not honouring the varargs ABI even with `-mabi=aapcs`. It was also quite a pain to get this compiler working in non-Linux environments, so... we ended up rebuilding the entire stack with Darwin ABI.  
And while doing so, we figured we might as well take the chance to change some other API points as well. One of those is `xnu_pf_maskmatch`, where we added an argument to give the patchset a name. The new prototype is:

    xnu_pf_patch_t* xnu_pf_maskmatch(xnu_pf_patchset_t *patchset, char *name, uint64_t *matches, uint64_t *masks, uint32_t entryc, bool required, bool (*callback)(struct xnu_pf_patch* patch, void* cacheable_stream));

We had also planned to have the last version of PongoOS open-sourced by now, but we've been otherwise occupied since the release of 0.11.0. I hope we can get that done rather soon, but in the meantime, could you try and see if changing that prototype (and preferably the build ABI) resolves your issue?

**Comment by Naville** [comment]
@Siguza Thanks for the heads up. Unfortunately that's a bit beyond what I'm capable of. Do I just fix ``xnu_pf_maskmatch`` calls in that module or is there anything else I should be aware of?

**Comment by Naville** [comment]
@Siguza I've modified the prototype, for the ABI part I just removed the ``-mabi=aapcs`` call which IMHO should default back to Darwin ABI since I'm building on Mac?

This time the module loads however the device reboots(I assume it panicked) a while after AppleLogo (I assume something is still broken when launchd is bootstrapping userspace)

**Comment by Naville** [comment]
@Siguza
