### ISSUE TITLE
CLI Argument for "Allow untested iOS/iPadOS/tvOS versions"???

### ISSUE THREAD

**Issue by SwiftMove** [checkra1n/BugTracker#1912]
As the title states, what is the CLI argument for the "Allow untested iOS/iPadOS/tvOS versions" option? I'm using checkra1n v0.12.1 and I don't see it listed in the usage info -> checkra1n -h

I've got an iPad Mini 4 on iOS 14.0.1 that won't boot via CLI but will boot if I use the GUI with the "Allow untested iOS/iPadOS/tvOS versions" option. So I'd like to know the CLI argument so that I can use that option via CLI.

**Comment by Siguza** [comment]
The CLI has no information whatsoever about the software installed on the device. The flag you're asking about doesn't exist there because it would do precisely nothing.  
If the GUI works but the CLI doesn't, it seems likely that you're improperly resetting the device when entering DFU. :/

**Comment by SwiftMove** [comment]
Bro WTF? I know you're a pretty smart guy, so I'm gonna assume that you've either you've had too much Vodka to drink tonight and just completely misread my post, or someone hacked your account and is just trolling lol. Let me try to break it down once more...

The checkra1n GUI has an option that you can enable that says "Allow untested iOS/iPadOS/tvOS versions". I want to know what argument I need to use to enable that option when running checkra1n via CLI, i.e. "checkra1n -c -v". I'm not sure why you would say "the flag you're asking about doesn't exist" when clearly it's right there in the GUI "Options" menu.

**Comment by Siguza** [comment]
You seem to have a misconception on what that flag actually does. Literally all it does is create an artificial barrier that doesn't let the user proceed unless they've acknowledged that their configuration isn't supported. There are zero functional differences. If you attached a device in recovery mode to the GUI, you'd get the exact same results.

Here, I made some flowcharts. This is how the GUI operates:

![GUI](https://user-images.githubusercontent.com/1659374/103135297-9ce2c980-46b7-11eb-96e5-2fec5bed58f5.png)

It's a simplified model, in reality there are many more checks and you can drop back to earlier stages if something failed, but you get the idea. Now here's how the CLI operates:

![CLI](https://user-images.githubusercontent.com/1659374/103135318-bd128880-46b7-11eb-8725-1c13b77cb677.png)

As you can see, at no point does it query the iOS version, and at no point does it attempt to verify that the installed OS is compatible with checkra1n. The CLI doesn't care, it assumes you're an advanced user and know what you're doing.

Given that, I don't understand what you would expect that flag to do on the CLI - since it lets you proceed either way.

**Comment by SwiftMove** [comment]
Ok I figured out whats happening. When I run checkrain via CLI, I put my device in DFU mode and then run "./checkrain -c -v". But it would always result in a "Timed out waiting for bootstrap upload" error every time. This is on an iPad Mini 4 with iOS 14.0.1 and I've never gotten this error when it was on iOS 13.x.x or lower. So I decided to give the GUI a try and had enabled the "Allow untested iOS versions" option in settings before Jailbreaking. I went thru the GUI Jailbreak process and everything worked fine, device Jailbroke without any errors and the checkra1n icon appeared. So immediately I thought, oh ok, it's because I need to use that "Allow untested iOS versions" setting on the CLI. But then of course I couldn't find the argument in the usage info since as you've stated it doesn't exist because it doesn't do anything and is only applicable to the GUI. Knowing that now, I realized the only other thing I did different when I used the GUI is that I had to put the device into Recovery Mode BEFORE I put it in DFU mode. So I decided to try doing that when using the CLI and now it works fine.

So that's why I thought the "Allow untested iOS versions" option was actually doing something, when in reality it was because I needed to put the device into Recovery mode BEFORE entering DFU mode. So why is it necessary to put the device into Recovery Mode before DFU mode now? I've never had to do that in the past. Is that some new requirement for iOS 14 or something?

**Comment by Siguza** [comment]
It's not _strictly_ recovery mode that is necessary, it's just that forcibly aborting a bood is bad. As best as we can tell, some hardware gets reset improperly and stops responding, but we haven't dug into the root cause.  
But some alternatives to recovery mode that should also work:
- `idevicediagnostics reboot`
- Turning the device off while connected to power (because it will actually reboot, which means you'll have to catch it between poweroff and LLB via button combo, and also know when you reach LLB at which point you have to hit the power button to actually continue booting)
- Plugging in a powered-off device and catching it right at boot (but this requires flawless split-second timing to catch it at the right moment)

**Comment by SwiftMove** [comment]
Ok, that makes more sense now. Thanks for taking the time to explain all that, much appreciated. =)
