### ISSUE TITLE
Setting boot-args via nvram causes checkra1n to freeze while booting

### ISSUE THREAD

**Issue by neaa44** [checkra1n/BugTracker#195]
iPhone 5s, iOS 12.4.3
checkra1n 0.9.1

1. do nvram boot-args"-v" in a terminal
2. re-run checkra1n
(i dont know if this applies to any other boot arguments) 

device should boot with (or ignore?) the set boot argument(s), but it hangs on "Booting..."

**Comment by nullpixel** [comment]
hi, this is not supported as checkra1n alters the boot arguments to boot the device.

**Comment by kpwn** [comment]
to clarify, hanging is not what should happen and i will probably look into why this happens since the nvram variable should be ignored completely by iBoot. anyway, it's highly recommended you don't touch nvram *AT ALL* on iOS, no matter of what jailbreak you're using, unless you are certain you're not fucking things up. 

but to be honest, the priority of me looking into this is probably the lowest priority of any issue in the entire bug tracker.

**Comment by Siguza** [comment]
I just tried setting `boot-args=-v` on an iPhone 6 on 12.4.3, everything still boots fine.

**Comment by neaa44** [comment]
> I just tried setting `boot-args=-v` on an iPhone 6 on 12.4.3, everything still boots fine.

i got it working, once, but now it keeps hanging again.. restoring to see if that helps
