### ISSUE TITLE
Lack of progress

### ISSUE THREAD

**Issue by jack254718** [checkra1n/BugTracker#2019]
Why has check rains updates and bug fixes slowed down to a halt. Still no windows release and still no fix on device crashes Fter 7 days of jb.

**Comment by teelekkung** [comment]
may be your tweak is the problem of 7 day , some tweak might call something same time and happened to crash then ios choose restart but not respring and entered safemode , Checkra1n is base on checkm8 in which checkm8 only run base on mac(not m1 and macos <= 11.2 for checkra1n 0.12.2 and below) and some linux, to port some code to new os is harder than you think because some function in mac and linux don't hav e in windows and windows begging for driver everything plug in to itself

**Comment by moabbikr** [comment]
> Why has check rains updates and bug fixes slowed down to a halt. Still no windows release and still no fix on device crashes Fter 7 days of jb.

100% agree, still cannot jailbreak my iPad mini 4 and no support for Big Sur 11.
