### ISSUE TITLE
Unable to Access Option Menu

### ISSUE THREAD

**Issue by raynebow11** [checkra1n/BugTracker#2021]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. usb drive plugged in and pc boots to usb drive
2. everything loads
3. once loaded the main screen appears (where it asks me to plug in phone) but unable to access options screen as keyboard doesnt work once script loads. I've pressed enter, pressed "O" for options and used arrows keys. Nothing works.

**What do you expect, and what is happening instead?**
supposed to be able to enter options screen so can choose setting for iphone 8 plus

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
unable to access options
**Any other info, error logs, screenshots, ...?**

**Comment by raynebow11** [comment]
forgot to add. Using latest version of Checkra1n. Ios is 14.3 on iphone 8 plus. Windows 10 64 bit connecting via USB plugged directly into computer

**Comment by teelekkung** [comment]
This issue is nothing to do with checkra1n but your pc and boot iso is, checkra1n native run on some linux and macos (macos <= 11.2. for checkra1n 0.12.2 and below) as the time now , Pls do some research about your pc and boot img to boot (some dev remove some driver for some device to make the iso smaller and fast to boot)Pls search and find new iso that work with your device. and close the issue because this is nothing to do with checkra1n itself
