### ISSUE TITLE
iPad Pro 1th generation won't boot.

### ISSUE THREAD

**Issue by Bogdan0w** [checkra1n/BugTracker#2109]
**Tell us about your setup:**
1. iPad Pro 1th Generation.
2. 14.5.1 & 14.6. Both not working.
3. Tested on 0.12.2, 0.12.3, 0.12.4.
4. MacBook Pro 2014 running macOS Big Sur 11.2.3.
5. New original Apple USB-A cable.

**What are the steps to reproduce the issue?**

Default steps to jailbreak with CheckRa1n.

1. Connect device to MacBook.
2. Open CheckRa1n.
3. Enabling "Allow untested iOS etc."
4. Click on "Start"
5. Enter device into DFU mode.
6. Wait until CheckRa1n jailbreak begins.

**What do you expect, and what is happening instead?**
CheckRa1n stuck at "Booting", and after that says Error -20. Device stuck at PongoOS.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

No.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

Yes.

**Any other info, error logs, screenshots, ...?**

**Comment by NewHospitals** [comment]
I have semi error for semi device. Does anybody know a solution to what we can do to fix it? Thank

**Comment by maodudo** [comment]
Tell us about your setup:

iPad Pro 1th Generation.(12.9)
14.5.1  not working.
Tested on 0.12.2, 0.12.3, 0.12.4.
hackintosh running macOS mojave 10.14.2
original Apple USB-A cable.
What are the steps to reproduce the issue?

Default steps to jailbreak with CheckRa1n.

Connect device to hackintosh
Open CheckRa1n.
Enabling "Allow untested iOS etc."
Click on "Start"
Enter device into DFU mode.
Wait until CheckRa1n jailbreak begins.
What do you expect, and what is happening instead?
CheckRa1n stuck at "Booting", and after that says Error -20. Device stuck at PongoOS.

Did you see a popup on the device stating it entered "Safe Mode" due to an error?

No.

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?

Yes.

Any other info, error logs, screenshots, ...?
![image](https://user-images.githubusercontent.com/84752914/119422778-5790f980-bd34-11eb-90ae-13f4f17ab31e.png)

**Comment by orione27** [comment]
Tell us about your setup:
iPad Pro 1st Generation.(9.7)
14.5.1 not working.

Tested on 0.12.3, 0.12.4.
Macmini running macOS mojave 10.14.6
original Apple USB-A cable.

What are the steps to reproduce the issue?

Default steps to jailbreak with CheckRa1n.

Connect device to Macmini
Open CheckRa1n.
Enabling "Allow untested iOS etc." (if disabled the same)
Enabling verbose mode (if disabled the same)
Click on "Start"
Entered device into DFU mode.
Wait until CheckRa1n jailbreak begins.

What do you expect, and what is happening instead?
CheckRa1n stuck at "Booting", and after that says Error -20. Device stuck at PongoOS.

Did you see a popup on the device stating it entered "Safe Mode" due to an error?
No.

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes.

Any other info, error logs, screenshots, ...?
Same as Maodudo above

**Comment by NewHospitals** [comment]
I have Same problem, please let me know if anything finds solution, it’s fact what not working for iPad Pro 1th generation.

**Comment by orione27** [comment]
I solved the issue for my ipadPro 1st gen based on A9X chip:

(1) install the latest version of checkra1n (currently 0.12.4)
(2) download a consolidated version of Pongo OS from here: 
https://github.com/checkra1n/BugTracker/files/6429930/Pongo.zip
(3) unzip it and put it in the Downloads folder (not inside the directory created unzipping it)
(4) open Terminal
(5) type the following command in terminal:

/Applications/checkra1n.app/Contents/MacOS/checkra1n -k /Users/xxxx/Downloads/PongoConsolidated.bin

replacing xxxx with your Home name (-k means forcing to use your consolidated Pongo version).

Magically DONE! Jailbroken ipad Pro is here! Then install Cydia from the checkra1n app...

Hope this will solve the issue for you too (and will help the developer to implement this option in the next version).
If so, enjoy!

**Comment by Bogdan0w** [comment]
@orione27 Seems pretty nice. I'm going to check it tomorrow (about 8-9 hours), and say if it solve the problem or not. Thanks for helping!

**Comment by Bogdan0w** [comment]
@orione27 has a solution, and it works. Thanks to Orione27!

**Comment by phvlkn** [comment]
Thank you so much, I thought that I could not restore my iPad, but thanks to you everything worked out !!!

**Comment by rorocheck** [comment]
How do I do this on Ubuntu? Links?

**Comment by phvlkn** [comment]
i'm on Mac, but try this:

1.  Download checkra1n for your system there https://checkra.in/releases/0.12.4-beta#all-downloads
2. download a consolidated version of Pongo OS from here and unzip it: https://github.com/checkra1n/BugTracker/files/6429930/Pongo.zip
3. run "sudo checkra1n -k xxxx" where xxxx is path to unziped consolidated version of Pongo OS

should work

**Comment by rorocheck** [comment]
Solved it already that way with all selections in options.

**Comment by printf147** [comment]
@rorocheck Did you solve it on Ubuntu？How to solve？

**Comment by rorocheck** [comment]
Solved on Ubuntu. Use all options in the menu (all, untested, verbose, skip
a11, dark block chain etc) and run checkrain on gui. So far has worked 4
times in a row.

**Comment by fennectech** [comment]
Thanks from manjaro!

**Comment by TKthudmaui** [comment]
How about Ipad 7th generation running on ios15 icloud lock, can someone help me

**Comment by e3boi** [comment]
@orione2 was wondering if you could help me I had the same issue with my iPad Pro 1st gen I followed your steps how ever I couldn’t unzip the Pongo package it wouldn’t let me unzip it. 
I still carried on with the other steps changed the xxx. With my host name it didn’t work, now it won’t let me run checkrain at all keeps saying invalid host name please help if you can thanks

**Comment by big-mond** [comment]
First run checkra1n in CLI mode. Don't know the Mac command but in Linux you add "-c" after checkra1n. What worked for me, after months of trying, was going through the DFU process while the ipad was already in DFU mode. So after it gets stuck, hold the power and home button for about 7 seconds, then let go of the power button while continuing to hold the home button. You should see the text in your terminal restart again. If it doesn't go the first time, keep repeating until it goes all the way through. It shouldn't take many attempts and I have made it work every time since I've used this method.

Device: iPad Pro 9.7, A9X, iOS 14.5.1

**Comment by TKthudmaui** [comment]
How about the iphone 8 plus with ios 15.2.1?

**Comment by Iopid777** [comment]
> I solved the issue for my ipadPro 1st gen based on A9X chip:
> 
> (1) install the latest version of checkra1n (currently 0.12.4) (2) download a consolidated version of Pongo OS from here: https://github.com/checkra1n/BugTracker/files/6429930/Pongo.zip (3) unzip it and put it in the Downloads folder (not inside the directory created unzipping it) (4) open Terminal (5) type the following command in terminal:
> 
> /Applications/checkra1n.app/Contents/MacOS/checkra1n -k /Users/xxxx/Downloads/PongoConsolidated.bin
> 
> replacing xxxx with your Home name (-k means forcing to use your consolidated Pongo version).
> 
> Magically DONE! Jailbroken ipad Pro is here! Then install Cydia from the checkra1n app...
> 
> Hope this will solve the issue for you too (and will help the developer to implement this option in the next version). If so, enjoy!

How the hell did you unzip?
