### ISSUE TITLE
Cant jailbreak - Error -31

### ISSUE THREAD

**Issue by nadunferz** [checkra1n/BugTracker#230]
**What device + iOS version are you on?**

**What checkra1n version are you using?**

**What are the steps to reproduce the issue?**
1.iOS 13.2
2.Checkra1n beta 0.9.2
3.Error - 31
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by perpelator** [comment]
@nadunferz Have you tried an original Apple Genuine cable? Is it lightning to USB-A (it has to be in order to get DFU mode to work it most cases)?

**Comment by nadunferz** [comment]
Yes but im running the tool using mac os on vmware.

**Comment by perpelator** [comment]
@nadunferz Unfortunately you cannot run this through VMware (or through any virtual machine, as said on checkra1ns website). I would recommend either waiting for the windows release in the upcoming week(s) or borrowing a friends Mac. If you have experience in using a Hackintosh, you could attempt that too.

**Comment by nadunferz** [comment]
Ohh ok thank you very much. Ill try it with friend’s mac.

**Comment by perpelator** [comment]
@nadunferz No problem.

**Comment by paulyc** [comment]
Yeah from my experience trying to get checkm8 to work on Linux, it's close but no tamale, it's too dependent on some kind of race condition timing, basically looks to me like checkm8 is going to have to be tweaked or rewritten to deal with linux libusb or OS driver or whatever is throwing a spanner in the works. 

As someone who has done a bit of embedded development before, I have run into plenty of these kind of nightmares, especially any time Python is involved, because USB, Python, the Python USB library, the C USB Library, and the OS USB driver all have the same problem: There are all these slightly different implementations of each one meaning there are thousands of possible combinations, and USB is not exactly a robustly designed or implemented protocol, so it ends up as this giant hairball where, you need one specific version of python one specific version of libusb one specific OS driver for the USB buses for every single different embedded device you want to communicate with, and no other device will work as long as a combination that works with another device is installed. So it's kind of a miracle that they have managed to get this to work as well as they have with so many different devices even made by the same manufacturer. Hats off, really!

I even had to make a fresh install of Mojave just to get this to work, after I had just had checkm8 working well enough to downgrade my ancient 5s to 10.3.3, on the same install, of the same MacOS on the same machine. Apparently, in the meantime I changed one of those things, probably installed a Mojave security update; installing security updates are generally a reliable way to break everything, so now it just doesn't work and I had to start from scratch.

All these hoops! Vs Android, fastboot flash.  But, I never had an Android phone that still worked at all after 2 years much less 6 years for this 5s with a firmware that has taken a licking and keeps on ticking, from 10 to 11, back to 10.3, to 12, and jailbroken again... The SecuROM exploit is a Godsend for sure, the Church should beatify whoever found that because it's a real miracle. An exploit that can't be patched and can't be bricked, doesn't get any better than that. It's nearly the computing equivalent of actually finding the holy grail.

**Comment by ethanhines** [comment]
I know you closed this because the op was using a vm. However I just used a true MacBook Air and got the same error -31 while trying to jailbreak an ipad 7th generation on 13.1.x. I request that you re-open this bug!
