### ISSUE TITLE
iPad won’t enter DFU mode

### ISSUE THREAD

**Issue by YessHiiHello** [checkra1n/BugTracker#2313]
**Tell us about your setup:**
1. iPad 5th gen
2. iOS 14.5
3. Checkra1n- version beta 0.12.4
4. MacOS Catalina 10.15.7
5. Either normal apple cable or some other I bought off Amazon. Both have worked in the many times I’ve jailbroken my iPad

**What are the steps to reproduce the issue?**
1. Connect iPad to Mac 
2. Start. I’ve started with different options safe mode by itself, untested by itself, no options, both untested and safe mode together
3. It goes into recovery mode I follow instructions but says it didn’t enter DFU mode.  

**What do you expect, and what is happening instead?**
I’ve done this multiple times though I don’t know if I’ve selected options or no options before but either way I’ve followed instructions as I’ve done many times. It shows the apple logo injected nothing though takes me back to my Lock Screen and says I didn’t enter DFU mode. I’ve done this on the same iPad, same iOS, same cable and now it’s not working. My iPad still remains the same and I’ve tried following the instructions again and again cause I thought maybe I was doing it wrong but no matter how I try it, it’s not working.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**  (No)

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** (Yes)

**Any other info, error logs, screenshots, ...?**  (No errors pop up)

**Comment by Sandwhich253989** [comment]
using check1x:
ipad 5th gen:, version 15.6
i can confirm , i have the same problem. i cannot get it into dfu no matter what :(

**Comment by sczze** [comment]
I figured out that the guide to enter DFU mode on checkr1an is not correct for my device (iPad Air 2, IOS 14) in terms of the number of seconds to hold down the button combination to enter DFU. For my iPad it was 8s for both home and power button instead of the 10s shown on the checkra1n application, and for home button only it was also different, I think it was 5s, but I'm not sure if I remembered that correctly. 

Ignore the time shown by checkra1n and try different combinations of seconds until it successfully enters DFU, might take a while, but it worked for me.

**Comment by YessHiiHello** [comment]
Okay I've solved the problem! I replaced my iPad screen like a year ago and I guess the button kinda unattached a little so it wasn't working very well so when I tried to put my iPad into DFU mode it wouldn't cause of it. I reopened it reattached it with tape to keep it in place and it's fixed, I can jailbreak it again!
