### ISSUE TITLE
Same issue as #136, but with a twist.

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#239]
**What device + iOS version are you on?**
iPhone 7 Plus; iOS 13.2.2

**What checkra1n version are you using?**
9.0
**What are the steps to reproduce the issue
1. Attempt to download tweak
2. Cydia returns any of their rejection statements 
3. Die a little on the inside
...

**What do you expect, and what is happening instead?**
I expect a fully functional jailbreak. Now as you mentioned in the response to issue #136:
 “checkra1n does not support jailbreaking on top of an already jailbroken device. To use things like Cydia, we recommend using your previous tool to unjailbreak.”
You offered advice on how to correct this issue by using the tool’s unjailbreak method , but what if that advice isn’t an option for someone else?. i previously had this iPhone 7+ jailbroken on unc0ver and ended up doing a factory reset before I unjailbroke the device. Now I’m running iOS 13.2.2 and after downloading unc0ver to attempt to restore rootfs, I am not able to do so as uncover doesn’t support that version of iOS. 

I straight up have no clue what I can do, or if there’s anything I can do in order to get Cydia in working order with this jailbreak.

**Any other info, error logs, screenshots, ...?**
No

**Comment by laelin** [comment]
Don’t know how your data is set up on your phone but I would say do a factory reset and start iPhone as New, don’t restore from any back up. To get your iCloud Drive pictures and stuff just log in to iCloud after setting up as NEW. Past jailbreak tweak injectors and substitutes seem to interfere with Cydia and tweaks themselves for checkra1n. Perhaps before the factory reset try going to cydia and removing any tweak injector/ substrate / substitute, everything from Electra and coolstar repo. The only substrate you need is the Cydia Substrate found in the checkra1n repo. Make sure all other substrates are removed! Then try tweaks.. if that doesn’t work... full file system restore.

**Comment by ghost** [comment]
Than you. I have already wiped the phone once and started the process as
new without any luck. I’ll try again a little later today and let you know
if it worked.

Thanks!
Christopher

**Comment by ghost** [comment]
So I was able to bypass all the issues successfully and it wasn't as complex as i was trying to make it be.  I simply ran the restore-fs feature from checkra1n since running that in unc0ver was not an option.  I also decided to stop using my older mac mini running 10.10 Yosemite and found my broken but newer MacBook Air running 10.14 Mojave and hooked it up to flatscreen to make the magic happen.  I also think that there is a possibility that when I first ran checkra1n right after it was released, I think I may have interrupted the "installing cydia" process somehow because I was gettin impatient, and this in turn caused other issues I had as well but hadn't discussed on this thread (Cydia was installed with **_NO PACKAGES PREINSTALLED WHATSOEVER_**, etc).  It took me a few tries to get my phone to calm itself long enough for me to be able to take it to the next level, but I finally got there.

Not sure i'm really of any help, but if you have any additional questions, please let me know.
**-cgris1982-**

**Comment by cgris1982** [comment]
Hey there, I just posted this response to the forum regarding my successful
resolution to the issue from the initial post:

So I was able to bypass all the issues successfully and it wasn't as
complex as i was trying to make it be. I simply ran the restore-fs feature
from checkra1n since running that in unc0ver was not an option. I also
decided to stop using my older mac mini running 10.10 Yosemite and found my
broken but newer MacBook Air running 10.14 Mojave and hooked it up to
flatscreen to make the magic happen. I also think that there is a
possibility that when I first ran checkra1n right after it was released, I
think I may have interrupted the "installing cydia" process somehow because
I was gettin impatient, and this in turn caused other issues I had as well
but hadn't discussed on this thread (Cydia was installed with *NO PACKAGES
PREINSTALLED WHATSOEVER*, etc). It took me a few tries to get my phone to
calm itself long enough for me to be able to take it to the next level, but
I finally got there.

Not sure i'm really of any help, but if you have any additional questions,
please let me know.
-cgris1982-
