### ISSUE TITLE
Ubuntu start checkra1n -c

### ISSUE THREAD

**Issue by oliviastampfli** [checkra1n/BugTracker#2409]
Hello Support team,

ich nutze Ubuntu auf Microsoft Windows [Version 10.0.19045.4842]
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64)
IPAD Version 4
checkra1n Version 0.12.4 beta

Kann weder das Directory anziehen noch diese in Linux mittels cd (change directory) auf folgendes Verzeichnis zugreifen:
cd C:\Users\Lenovo\Downloads\
 

olivia@DESKTOP-VUHDOGA:~$ cd C:\Users\Lenovo\Downloads\checkra1n -c
-bash: cd: too many arguments
olivia@DESKTOP-VUHDOGA:~$ C:\Users\Lenovo\Downloads\checkra1n -c
C:UsersLenovoDownloadscheckra1n: command not found
olivia@DESKTOP-VUHDOGA:~$ C:\Users\Lenovo\Downloads\checkra1n.exe -c
C:UsersLenovoDownloadscheckra1n.exe: command not found
olivia@DESKTOP-VUHDOGA:~$ cd C:\Users\Lenovo\Downloads\
> checkra1n.exe -c
-bash: cd: too many arguments
olivia@DESKTOP-VUHDOGA:~$ cd C:\Users\Lenovo\Downloads\
> checkra1n -c
-bash: cd: too many arguments

Somit funktioniert diese Ubuntu Version nicht.
Was kann ich tun?

Lg Olivia Stampfli

**Comment by Siguza** [comment]
You have simply failed to type any valid command into your shell. But don't bother with WSL, it won't work. checkra1n needs fine-grained control over the USB driver in order to pull off the exploit, and WSL can't provide that. In theory you could have a VM with USB passthrough, but that is something that Windows doesn't support AFAIK (and it would also mean that you then have no USB on the host). So you'll need a bare metal Linux installation.
