### ISSUE TITLE
Cannot access photos in 3rd party apps from App Store

### ISSUE THREAD

**Issue by justindal** [checkra1n/BugTracker#263]
iPhone 6S Plus, iOS 13.2

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1. Open a 3rd party app (Instagram, Snapchat)
2. Try to access photos somehow (posting)
3. No photos show

**What do you expect, and what is happening instead?**
Photos cannot be accessed but still can be seen in System apps like messages, photos
**Any other info, error logs, screenshots, ...?**

**Comment by greenywd** [comment]
This happens with me too on my iPhone X (iOS 13.2.2, 0.9.2). However, rejailbreaking appears to fix it for a small period of time.

**Comment by zhtengw** [comment]
I confirmed this with iPhone SE on iOS 13.2.2, jailbroken with both 0.9.1 and 0.9.2.

**Comment by zhtengw** [comment]
I found out that it is caused by the tweaks "Liberty Lite". Uninstall "Liberty Lite" then apps can access photos again.

**Comment by Shadowedstalker** [comment]
I have Liberty Lite and No issue here. It could be caused by more than one tweak.

Try this 

Install iCleanerpro http//ib-soft.net/cydia/
Open iCleanerPro
Click + (lower Left Corner
Click Cydia Substrate Addons
Tap ALL
Tap Apply
Tap yes.

After respring all tweaks are disabled.

Test App. If it works it's one of YOUR tweaks causing the issue.

Go back into iCleanerPro and turn your tweaks on one by one, testing the App after each one. 
This way you can narrow down what is causing the problem for YOU.
