### ISSUE TITLE
Taptic Engine and Cydia not working after second jailbreak

### ISSUE THREAD

**Issue by birkhofflee** [checkra1n/BugTracker#272]
**What device + iOS version are you on?**
iPhone 8 Plus Global, iOS 13.2.2

**What checkra1n version are you using?**
0.9.2 Beta

**What are the steps to reproduce the issue?**
Can't really say how to reproduce, but this is what happened. I jailbroke my device using checkra1n the first time yesterday, installed some tweaks and went to bed. The second day, the device died out of battery, and when I re-jailbreak again, strange things happened:

1. Taptic Engine not working
2. Sometimes Wi-Fi doesn't work until the device booted for a couple of minutes
3. Can't re-install Cydia, can't open Cydia, can't open any tweak apps. (Better in a video: https://i.imgur.com/xAM4Pgu.mp4)
4. Booting sometimes take a super long time, and it's like: Apple Logo -> checkra1n boot screen -> Apple Logo (a couple of minutes) -> black screen for a second -> Apple Logo (a couple of minutes, at this stage I can already SSH into the device) -> Lock Screen

**What do you expect, and what is happening instead?**
Taptic Engine/Wi-Fi/Cydia should be working properly. but they aren't.

**Any other info, error logs, screenshots, ...?**
A video was provided above. I tried to use the safe-mode boot sequence (vol+ while booting) but it doesn't seem to work. Tried to `killall -SEGV SpringBoard`, won't work either.

**Comment by TaeaminExie** [comment]
I also have had the same problem, I had downloaded a bad tweak, but with Checkrain 0.9.2 tried to go into safemode which i dont know if it worked or not because when my phone turned on finally, my haptic feedback wasnt working, my home button wouldnt vibrate, couldnt adjust my volume, and my wifi was grayed out and i couldnt turn it on at all. I tried deleting the bad tweak and rejailbreaking and it still did the same thing. After i tried jailbreaking with 0.9.1 it wouldnt work anymore and same with 0.9.0 so now i cant jailbreak at all. I restored my phone through itunes and tried again with 0.9.2 and it goes through but when its booting it will take a long time and then not even boot into jailbroken mode it will go to default IOS

**Comment by birkhofflee** [comment]
Volume buttons don’t work for me either.

**Comment by TaeaminExie** [comment]
I really hope that this didnt mess up my chances to get a jailbreak for iphone 8, ive been waiting for so long for this

**Comment by gnutnos98** [comment]
me either! :(

**Comment by gnutnos98** [comment]
#231 duplicate

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
