### ISSUE TITLE
same non responsive screen/ faceid not working/ no app 

### ISSUE THREAD

**Issue by mrcm311** [checkra1n/BugTracker#311]
**What device + iOS version are you on?**
iOS 13.2.2 Iphone x

**What checkra1n version are you using?**
0.9.3.2
**What are the steps to reproduce the issue?**
1. jailbreak then boots up to non responsive screen
2. Did dfu mode from non responsive screen / then restarted checkra1n to re jailbreak
3. screen then works fine but message pops up with faceid not working. and Checkra1n app is no where to be found. 
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by HeyItsMicro** [comment]
while ive been experiencing the non responsive screen since 0.9.2, now face id isn't working on 0.9.3.2

**Comment by Cupcak3** [comment]
I've gotten 0.9.3.2 to work on iPhone X 13.2.2. Here's how I got it to work:

Attempt 1: Jailbroke but still had screen unresponsive bug.
Attempt 2: **_Entered DFU straight from attempt 1, not from stock_**. Jailbroke, no unresponsive screen bug, but FaceID broke (Could not activate FaceID on this device).
Attempt 3: _**Entered DFU straight from attempt 2, not from stock**_. Jailbroke, no unresponsive screen bug, FaceID appeared not set up (No "Could not activate FaceID on this device" message). I set up FaceID and it works fine.

A note, I followed [this](https://www.reddit.com/r/jailbreak/comments/duceo2/tip_for_checkra1n_dfu_mode/) to get into DFU mode instead of the instructions within the Checkra1n app.

Hope this helps anyone.

**Comment by kpwn** [comment]
Does FaceID stay working past a reboot?

**Comment by Cupcak3** [comment]
I have not rebooted my phone since attempt 3.

**Comment by HeyItsMicro** [comment]
please reboot it so we can help the devs fix these issues (kpwn is @qwertyoruiopz on twitter btw)

**Comment by Cupcak3** [comment]
I rebooted into stock and then ran the jailbreak. FaceID stayed working, no unresponsive screen bug.

**Comment by halfbread10** [comment]
> I've gotten 0.9.3.2 to work on iPhone X 13.2.2. Here's how I got it to work:
> 
> Attempt 1: Jailbroke but still had screen unresponsive bug.
> Attempt 2: **_Entered DFU straight from attempt 1, not from stock_**. Jailbroke, no unresponsive screen bug, but FaceID broke (Could not activate FaceID on this device).
> Attempt 3: _**Entered DFU straight from attempt 2, not from stock**_. Jailbroke, no unresponsive screen bug, FaceID appeared not set up (No "Could not activate FaceID on this device" message). I set up FaceID and it works fine.
> 
> A note, I followed [this](https://www.reddit.com/r/jailbreak/comments/duceo2/tip_for_checkra1n_dfu_mode/) to get into DFU mode instead of the instructions within the Checkra1n app.
> 
> Hope this helps anyone.

Tried this method but was stuck at attempt 2. Turned off Face ID and verbose boot and it worked first try.

**Comment by gurkentier** [comment]
Try entering DFU mode using the checkra1n tool, it solved all of my issues!

**Comment by halfbread10** [comment]
> Try entering DFU mode using the checkra1n tool, it solved all of my issues!

that has never worked for me. phone always boots up in regular mode

**Comment by kratos9394** [comment]
first step，enter dfu mode always without checkra1n，then click start，no errors poped out even once

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
