### ISSUE TITLE
About battery detailed report repair

### ISSUE THREAD

**Issue by Zason-Lee** [checkra1n/BugTracker#328]
Find the directory "Library/LaunchDaemons/", modify "com.apple.jetsamproperties.XXX.plist" (the corresponding device model, a total of 2 files), open the file and find "ActiveSoftMemoryLimit", "InactiveHardMemoryLimit", these two values The battery details report can be repaired by changing to 100 and saving.

**Comment by kratos9394** [comment]
which values  we should change?there are a lot of  "ActiveSoftMemoryLimit", "InactiveHardMemoryLimit" ,what <key>  we should modify

**Comment by Zason-Lee** [comment]
Change the "ActiveSoftMemoryLimit" and "InactiveHardMemoryLimit" values to 100

**Comment by Zason-Lee** [comment]
Some devices may have a total of 3 files and need to be modified. If the modification is invalid, it may be that the adjustments you have installed have more impact. You can try changing to a higher value. After the modification, you need to restart the device and re-execute the jailbreak operation.

**Comment by littlelailo** [comment]
I think this isn't a proper way to fix this. The issues are most likley caused by a tweak that uses to much memory and that's why jetsam kills the process. I also think that unexperienced users might fuck up their device because jetsam can't read the plists anymore, that's why I will close and look this.
