### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by JiZZER6** [checkra1n/BugTracker#456]
i did everything right but it saying connection refused what should i do?
<img width="193" alt="Bildschirmfoto 2019-11-18 um 16 37 19" src="https://user-images.githubusercontent.com/49577000/69066572-cbf12b00-0a21-11ea-9772-ca16ca5167cb.png">

**Comment by boierito** [comment]
Please specify what are you doing to get this error

**Comment by JiZZER6** [comment]
My cydia cracks after i did n reboot on my ip6s and it says springboard
failed to reboot and i did restart and bow my cydia wont open anymore what
should i do?


boierito <notifications@github.com> schrieb am Mo. 18. Nov. 2019 um 4:41 PM:

**Comment by JiZZER6** [comment]
I just tried to install zeppelin and it was succesfully installed so i need
to reboot my device after a reboot there was nothing and when i try to open
the cydia it crashes everytime

Ganbaatar Ganbileg <ganbileg764@gmail.com> schrieb am Mo. 18. Nov. 2019 um
4:44 PM:

**Comment by DanyL** [comment]
checkra1n is a semi-tethered jailbreak which requires you to re-run the tool every time you want to boot into a jailbroken mode, otherwise Cydia and all other 3rd party apps/tweaks wouldn't work.
As for the connection refused error, you are using the wrong port, SSH is running on port 44.

Next time please properly describe your problem, I don't need to guess what your'e asking about.

**Comment by JiZZER6** [comment]
okay but how can i uninstall it?


Am Mo., 18. Nov. 2019 um 16:58 Uhr schrieb Dany Lisiansky <
notifications@github.com>:

**Comment by JiZZER6** [comment]
u will probably say with checkra1n app but is vanished from my springboard


Am Mo., 18. Nov. 2019 um 17:03 Uhr schrieb Ganbaatar Ganbileg <
ganbileg764@gmail.com>:
