### ISSUE TITLE
Possible Backdoor Left open

### ISSUE THREAD

**Issue by kr3ack** [checkra1n/BugTracker#664]
Hey,

I'm not sure if I was suppose to suppose to close something after ruuning the iproxy file. but my dumbass ran the file off the machine and I think my device is now comprimised with a upnp virus or running script somewhere. I can't even beat my meat in private. I killed the ssh agent in the monitor but it nothing changes. I know what I'm saying its a bit vague but all I can tell you is that they're capaturing device info tracing calls, heaping the area. If its you guys please let me know. Thanks

**Comment by Siguza** [comment]
What are you basing your assumptions on? Is it possible that you're received threats by email saying that you've been hacked and need to send someone bitcoins or iTunes gift cards or something along those lines? In that case, it's a scam and you can safely ignore it.

I'm gonna go ahead and close this since I'm confident that whatever you're experiencing is unrelated to checkra1n.
