### ISSUE TITLE
iPad Pro 1gen. no jailbreak

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#670]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Pro 1.Gen
2. On what version of iOS is it?
13.3
3. What version of checkra1n are you using? GUI or CLI?
0.9.7. GUI & CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Macbook Pro 2017. 10.15
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C    & USB-C to usb A & USB-C adapter

**What are the steps to reproduce the issue?**
1. use the same setup as me?

...

**What do you expect, and what is happening instead?**
USB-C Problem?
 Iphone7 works great.

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**
```
# Checkra1n beta 0.9.7
#
# Proudly written in nano
# (c) 2019 Kim Jong Cracks
#
#========  Made by  =======
# argp, axi0mx, danyl931, jaywalker, kirb, littlelailo
# nitoTV, nullpixel, pimskeks, qwertyoruiop, sbingner, siguza
#======== Thanks to =======
# haifisch, jndok, jonseals, xerub, lilstevie, psychotea, sferrini
# Cellebrite (ih8sn0w, cjori, ronyrus et al.)
#==========================

 - [*]: Waiting for DFU devices
 - [*]: Exploiting
 - [*]: Checking if device is ready
 - [*]: Setting up the exploit (this is the heap spray)
 - [*]: Right before trigger (this is the real bug setup)
 - [*]: Entered download mode
 - [*]: Booting...
 - [!]: Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode pass the '-s' option) (error code: -20)
 - [!]: Unknown error (error code: -20)
```

**Comment by quilenle** [comment]
Could you try to run the command ./checkra1n -s

**Comment by songonic** [comment]
> Could you try to run the command ./checkra1n -s

the same result


 - [*]: Waiting for DFU devices
 - [*]: Exploiting
 - [*]: Checking if device is ready
 - [*]: Setting up the exploit (this is the heap spray)
 - [*]: Right before trigger (this is the real bug setup)
 - [*]: Entered download mode
 - [*]: Booting...
 - [!]: Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode pass the '-s' option) (error code: -20)
 - [!]: Unknown error (error code: -20)


I buy a new adapter&cabel today, maybe that will fix it.

**Comment by ghost** [comment]
Got Fixed....
It Works with a USB-C to USB-A adapter and a USB-A to Lightning cabel
