### ISSUE TITLE
checkra1n 0.9.8 gives error -20, checkra1n 0.9.7 works without problem

### ISSUE THREAD

**Issue by Panja0** [checkra1n/BugTracker#835]
**_1. What iDevice are you using?_**
iPhone X
Global - iPhone 10,6

**_2. On what version of iOS is it?_**
At the moment  13.3.1 (but problem is present on 13.3 as well)
This is a clean install, install through ipsw **without** restoring a backup

**_3. What version of checkra1n are you using? GUI or CLI?_**
v0.9.8 - GUI

**_4. What is your host system (OS version? Hackintosh? VM? etc.)?_**
MacBook Pro early 2015 - MacOS 10.13.6

**_5. How are you connecting to the device?_**
Official Apple USB to lightning cable

**_What are the steps to reproduce the issue?_**
1. Fresh install iOS 13.3 or 13.3.1 through ipsw in iTunes
2.  Set up phone (settings etc)
3. Jailbreak with checkra1n 0.9.8 for the first time
4. Install Cydia from within the checkra1n app
5. Open Cydia and install all Cydia recommended and needed updates
6. Respring
7. Install 1 tweak that is on the [compatibility sheet](https://docs.google.com/spreadsheets/d/1qce_nLb2WZfQ6ri8R3_BkUHMxEHMTbJK_6DnysgCiL8/htmlview) for instance NoDNDBanner. This will automatically install Cydia Substrate and Substrate Safe Mode.
8. Respring
9. At this point no issues
10. Reboot phone
11. Run checkra1n
12. It will time-out and give you error -20 (incompatible tweak)

_**What do you expect, and what is happening instead?**_
I expect it to jailbreak without problems, because there are no incompatible tweaks installed.
Instead it times out and gives me error -20

_**Does the issue also occur if you enable Safe Mode?**_
No, booting/jailbreaking in safe mode works.

_**Any other info**_
After removing checkra1n 0.9.8 from my Mac and installing the previous version (0.9.7) solves my problem. I can install multiple tweaks (compatible) and jailbreak without problems on 0.9.7

**Comment by FraserEmbrey** [comment]
I have been having this issue as well. I didn't fresh install.

### 1. What iDevice are you using?
iPhone X

### 2. On what version of iOS is it?
13.3.1 (upgrade from 13.3)

### 3. What version of checkra1n are you using? GUI or CLI?
v0.9.8 — GUI & CLI
v0.9.7 — CLI

### 4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacBook Pro 2018 — macOS 10.15.3
Desktop linux machine — pop!_os

### 5. How are you connecting to the device?
Official Apple USB-C to lightning cable (macOS)
Official Apple USB to lightning cable (linux)

### What are the steps to reproduce the issue?
1. Boot iPhone to normal mode
1. Connect to computer with checkra1n installed
1. Jailbreak with checkra1n 0.9.8
1. Jailbreak times out, gives error -20
1. Jailbreak seems to stick on allocated static region for rdisk
1. Rinse and repeat brings no joy

### What do you expect, and what is happening instead?
I expect the jailbreak to work fine, not leave my phone stuck displaying the jailbreak text and not booting
Instead the phone is stuck displaying allocated static region for rdisk as the last line

### Does the issue also occur if you enable Safe Mode?
No, booting/jailbreaking in safe mode works.

### Any other info
+ checkra1n 0.9.7 is and was working fine with the same iPhone and the same tweaks (can only test on mac)
+ V0.9.8 CLI will give an error of no device UUID if I fail to enter DFU first time, but then lets me go back to the start screen and works fine
+ v0.9.8 worked once and seemed fine but I needed to properly restart my iPhone and since then I have been unable to get it to work
+ Interestingly the text during the jailbreak when using 0.9.7 and below is a normal readable size, on 0.9.8 it is very small
+ Unsure what the option for a dark blockchain is, it is on by default, turning it off lead to a crash due to a segmentation fault. Using CLI (text) after while still in DFU (assumed) lead to errors -26 & -31
+ CLI (text) has worked but unsure if this is a fluke as I tried again and the same issue occurred

**Comment by computersteve** [comment]
Same problem..

**Comment by baso2000** [comment]
same problem I am unlike to jailbreak V 0.9.8 and return to V 0.9.7

**Comment by DanyL** [comment]
Could you please share what kind of models you all have? (GSM or Global).

**Comment by Panja0** [comment]
For me: Global - iPhone 10,6

**Comment by computersteve** [comment]
For me: Global - iPhone 10,6

**Comment by sbingner** [comment]
To make sure it's not just me - can you guys try booting with verbose boot option on and tell us if it fixes it for you?

**Comment by ddsFs1** [comment]
> To make sure it's not just me - can you guys try booting with verbose boot option on and tell us if it fixes it for you?

I have the same problem and the same conditions as in [issue#830](https://github.com/checkra1n/BugTracker/issues/830), all other versions work fine but there are only 0.9.8 problems with jailbreak, in the gui version of checkra1n error -20 pops up and on the phone in verbose boot error "hfs mounted checkra1nrd"

**Comment by Panja0** [comment]
@sbingner 

Just tried:

v0.9.8 (gui on MacOS) **with** verbose = works
v0.9.8 (gui on MacOS) **without** verbose = does not work

Could you explain why verbose works and without verbose it does not work?
What does verbose do in this case?
I thought verbose mode provides additional details as to what the device is doing and outputs this on screen.

**Comment by FraserEmbrey** [comment]
I have an A1901 iPhone. I have tried with verbose mode and it did work but it has occasionally worked, maybe 1/20 and I really didn't want to have to try another 20 or so times to get that 1. If it appears that verbose is indeed a fix and not just coinciding with a good jailbreak attempt, I will also try

**Comment by sbingner** [comment]
It fixes it but it's not a fix... and no i don't know why, it's really quite strange.  But yeah, just leave verbose boot on when you jailbreak and you should have the same reliability you had on 0.9.7 for now

**Comment by PencilNotPen** [comment]
I also have this issue, iPhone X, iOS 13.3. Jailbreaks fine first time round, as soon as Substrate is installed (even if with no other tweaks), hangs and get error -20.

Removing Substrate and all tweaks makes it jailbreak again immediately.

Edit: As mentioned above, the 'fix' works. Enabling "Verbose mode booting" allows it to jailbreak. The device also does not respect the option being unticked, and always shows text on the screen regardless, but only succeeds when it is ticked. Strange bug.

**Comment by computersteve** [comment]
v0.9.8 (gui on MacOS) with verbose = works on my iPhone X as well.. So this must be a bug.

**Comment by sbingner** [comment]
If you guys update substrate (via safe mode or verbose boot) it should fix the problem for you - please confirm?  The only change is that when it starts up it waits for confirmation that it finished starting vs confirmation that it spawned substrate before continuing

**Comment by Panja0** [comment]
I've updated Substrate and can confirm I can now jailbreak normally (without verbose) on v0.9.8!
Thanks @sbingner

**Comment by gustavolessa23** [comment]
I've got the same problem on iPhone 7. I've jailbroken it using 0.9.8 a few times, but suddenly I couldn't anymore. Tried everything I found online.
I can jailbreak using Safe Mode and that's the only way. When I reinstall Substrate from Cydia on Safe Mode, the phone is back to jailbroken state, but Cydia crashes on launch.

Any thought on how to fix it?

Thank you very much!
