### ISSUE TITLE
Error -79

### ISSUE THREAD

**Issue by JKakaofanatiker** [checkra1n/BugTracker#849]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone SE
2. On what version of iOS is it?
13.2
3. What version of checkra1n are you using? GUI or CLI?
GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu 18.04 LTS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
1. Start Checkra1n
2. Try to jailbreak

**What do you expect, and what is happening instead?**
I expected it to jailbreak my device successfully

**Does the issue also occur if you enable Safe Mode?**
No

**Any other info, error logs, screenshots, ...?**
I have verbose boot activated and it says "AssertMarcros: error: 0" many times

**Comment by JKakaofanatiker** [comment]
EDIT: Also happens on macOS Mojave. Checkra1n gives me a different error code.

**Comment by danieltroger** [comment]
I have the same issue. Exact same setup except on iOS 13.2

**Comment by DMcolmi** [comment]
Same issue.

iPhone 7
Ios 13.-
GUI
Ubuntu 18.04.3 LTS
Swap Pcs, cables, usb A ports..

![IMG_20200209_102254](https://user-images.githubusercontent.com/47849352/74099906-b8d58f00-4b28-11ea-9051-17b6f3456189.jpg)

**Comment by jkiddin** [comment]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6S
2. On what version of iOS is it?
iOS 13.0
3. What version of checkra1n are you using? GUI or CLI?
GUI 0.9.8 + Bootra1n
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Kali Linux (usb)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
1. Run checkra1n
2. Go through steps to get into DFU mode
3. It states that it is downloading and then it shows Error Code -79 and returns my iPhone to it's lock screen.
...

**What do you expect, and what is happening instead?**
I expected for my phone to be jailbroken (duh). It shows the checkra1n logo on the phone for a good half-second and then just returns to the Apple logo. 

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
Tried to used bootra1n and another computer. bootra1n gave me the same error code (-79). On the GUI, I had error codes -77, -78 and -79. -77 fixed by removing passcode, -78 fixed by reopening checkra1n, but I can't fix -79.

(dumping my issue here too lol)

**Comment by JKakaofanatiker** [comment]
Also happens on Ubuntu 16.04 (cli)

**Comment by JKakaofanatiker** [comment]
Also happens with checkra1n 0.9.8.1

**Comment by Viktova** [comment]
https://github.com/checkra1n/BugTracker/issues/798#issuecomment-596006729

**Comment by JKakaofanatiker** [comment]
Restoring rootFS helps. I jailbroke again after and installed all my tweaks again. No probrems.
