### ISSUE TITLE
Ability to run checkra1n without having to put your device in recovery mode first

### ISSUE THREAD

**Issue by mpelteshki** [checkra1n/BugTracker#860]
I just got a USB-C to lightning cable from Apple so that i can jailbreak through my macbook. The problem is that these do not let you get into dfu mode. I would like you to consider adding an option to let us run checkra1n directly from dfu mode(as in earlier versions) as otherwise it’s practically impossible to jailbreak through a modern macbook.

**Comment by ann0see** [comment]
Does the cli version work (--cli)?

**Comment by mpelteshki** [comment]
What do you mean exactly? The problem is with the cable as far as I am concerned(some of the developers said that usb c to lightning cables bought from Apple don’t let you get into dfu mode). I have trued the cli version but the result is basically the same.

**Comment by mpelteshki** [comment]
Oh nevermind. It did work. I just didn’t get what you were saying at first. Anyways, thanks. I still think this should be made more easily accessible by the end user though.

**Comment by Siguza** [comment]
So, there are two separate issues.

- The Apple USB-C-to-Lightning cable somehow makes the device not detect a cable connected, and so it can't enter DFU mode with it - there is absolutely nothing we can do about that.
- Our GUI rejects devices that are already in DFU when connected, because it's possible to get your device into DFU without properly resetting the SoC, and that can lead to TouchID, FaceID, or even the touchscreen not working, we have no way to detect that after the fact, and a lot of users complained about it. If you feel like you know what you're doing and want to bypass this, use `-c`.

Either way, I'm marking this as working as intended/won't fix.
