### ISSUE TITLE
An idea, don't know if it will work...

### ISSUE THREAD

**Issue by mechite** [checkra1n/BugTracker#876]
Could you use Windows 10s built in Linux bash to execute the CLI version of CheckRa1n? This just came to me, as the kernel driver should work just fine under the bash, no? Also, will this provide low enough level USB access to perform the exploit? Something is telling me that it is a no.

You could release a version of CheckRa1n that uses CLI to do the exploit, using Linux, that is run from a small .iso file, added to the BCD (however, doing this on a UEFI computer will NOT work).

I have tested a third-party program called BootRa1n using this BCD trick, and it worked like a charm, so I feel like it might be the way to go before the actual Windows release.

**Comment by ann0see** [comment]
As far as I know, this has been tried and doesn‘t work (yet), as you said.

**Comment by acharya8848** [comment]
WSL doesn't support USB passthrough, which renders the tool useless.

**Comment by Siguza** [comment]
WSL has no USB support whatsoever natively, the only way to bring USB support to it is by relaying it through something that can interface with the Windows APIs. And since the Windows APIs don't allow us to violate the USB spec in the way we need to, this still has all the challenges of making checkra1n run on Windows natively.
