### ISSUE TITLE
Screen freezes after checkra1n boot screen completes

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#90]
**What device + iOS version are you on?**
iPhone 7+; iOS 13.2.2

**What are the steps to reproduce the issue?**
1. Install tweak (I cannot remember what the tweak was at the moment)
2.reset springboard
3. Problem begins 
...

**What do you expect, and what is happening instead?**
Checkra1n successfully jailbreaks the phon, but the screen freezes when saying that it’s booting, and then ultimately goes black and reboots into normal mode.

**Any other info, error logs, screenshots, ...?**
Usually in this situation I would run the jailbreak without tweaks and pinpoint the tweak and delete it. Is there a way to do that for this jailbreak?

no other info at this time.

**Comment by nullpixel** [comment]
Hi, if you installed a tweak which is causing these issues then this guide should help you resolve that: This is caused by a faulty tweak which is not checkra1n's fault. Please follow this guide to resolve the issue: https://www.reddit.com/r/jailbreak/comments/ducjw9/tutorial_how_to_enter_safe_mode_and_remove_bad/

**Comment by ghost** [comment]
I don’t know that the tweak was the reason.  I was just stating the order of the processes before the issue.
