### ISSUE TITLE
Will not Boot -- checkra1n freezes at "Booting" stage

### ISSUE THREAD

**Issue by jphil16** [checkra1n/BugTracker#934]
[Help] A new error. Can’t boot after 0.9.8 beta. Each time the process- at the part— where it says “booting”, before the boot logos show on the device, the “Booting....” flashes every second and does not proceed any further. After a long time, it finally gives me an error code of -12. Any Ideas?
![Screen Shot 2020-02-20 at 3 34 38 AM](https://user-images.githubusercontent.com/24636965/74991047-c842bb00-53f9-11ea-9b8f-3a0086facc28.png)

**Comment by Mikagreat** [comment]
@jphil16 If your OS version is 13.4 beta?

**Comment by elkinguerrab** [comment]
me too

**Comment by AdvancedCracker** [comment]
iPhone X - iOS 13.4 Beta 2. Entered Download Mode Booting cycle. then error -12. Late 2008 MacBook, macOS Catalina 10.15.1 (dosdude1 Catalina Patcher used on this MacBook). checkra1n version 0.9.8. could it be that apple seemed to patch the SEP processor in all phones to prevent the phones from being jailbroken again? because if so, this phone is permanently marked as jailbroken and yet won't be able to use Zelle or FaceID on banking apps (a-bypass worked to fix these issues; banking apps such as Chase, Huntington, Varo, etc.). im hoping that this bug is just OS based and does not mean this bug is patched because apple patched SEP

**Comment by Siguza** [comment]
13.4 support isn't out yet, see #877.
